### PR TITLE
Fix Search

### PR DESCRIPTION
**Pull request by MrSunshyne**
This PR fixes the Search functionality not working as intended. 
The issue was that it was still using the old(vue2) v-model syntax.

### CODE REVIEW

**Comment by MrSunshyne** [comment]
@kiwina please take a look

**Comment by sprice88** [comment]
<vgt-global-search
          @on-keyup:modelValue="searchTableOnKeyUp"
          @on-enter:modelValue="searchTableOnEnter"
          v-model="globalSearchTerm"
          :search-enabled="searchEnabled && externalSearchQuery == null"
          :global-search-placeholder="searchPlaceholder"
      >

you also need to update the event subscribers to this on line 50 of Table.vue otherwise the on-search event does'nt get outputted

**Comment by luisdnodrizat** [comment]
thank you guys, saved me a lot of work @MrSunshyne @sprice88

**Comment by MrSunshyne** [comment]
Closing to clean up my "PR" tab.

**Pull request closed without merging**
